<?php

function computed_field_field_r_display($field, $entity_field_item, $entity_lang, $langcode, $entity){
  return $entity_field_item['value'];
}
function computed_field_field_s_display($field, $entity_field_item, $entity_lang, $langcode, $entity){
  return $entity_field_item['value'];
}
function computed_field_field_t_display($field, $entity_field_item, $entity_lang, $langcode, $entity){
  return $entity_field_item['value'];
}

function computed_field_field_r_compute(&$entity_field, $entity_type, $entity, $field, $instance, $langcode, $items){
  $wrapper = entity_metadata_wrapper($entity_type,$entity);
  $x = $wrapper->field_x->value();
  $y = $wrapper->field_y->value();
  $entity_field[0]['value'] = $x + $y;
}

function computed_field_field_s_compute(&$entity_field, $entity_type, $entity, $field, $instance, $langcode, $items){
  $wrapper = entity_metadata_wrapper($entity_type,$entity);
  $x = $wrapper->field_x->value();
  $y = $wrapper->field_y->value();
  $z = 0;
  $wrapper_foo = $wrapper->field_z;
  $foo_id =  $wrapper_foo->raw();
  if (!empty($foo_id)) {
  	$z = $wrapper_foo->field_a->value();
  }
  $entity_field[0]['value'] = $x + $y + $z;
}

function computed_field_field_t_compute(&$entity_field, $entity_type, $entity, $field, $instance, $langcode, $items){
 $wrapper = entity_metadata_wrapper($entity_type,$entity);
  $x = $wrapper->field_x->value();
  $y = $wrapper->field_y->value();
  $zz = 0;
  $wrapper_bars = $wrapper->field_zz;
  $bar_ids =  $wrapper_bars->raw();
  if (!empty($bar_ids)) {
  	for ($i=0; $i < count($bar_ids); $i++) { 
  	  $zz += $wrapper_bars[$i]->field_b->value();
  	}
  }
  $entity_field[0]['value'] = $x + $y + $zz;
}
